#!/usr/bin/env bash
# User-facing facade
# TODO: Add --help

# Ensure x11vnc-run.sh exists in PATH
export PATH="$PATH:$(dirname $(readlink -f ${BASH_SOURCE[0]}))"

# Default but overridable
XVFB_SERVER_ARGS=${XVFB_SERVER_ARGS:--screen 0 1024x768x24}

# 1. Start up virtual X frame buffer, allocating new $DISPLAY
# 2. Start the payload command $@ under this new $DISPLAY
# 3. Start VNC server, attched to $DISPLAY
# 4. Upon payload's termination, kill VNC and xvfb
xvfb-run --server-args="$XVFB_SERVER_ARGS" $XVFBRUN_ARGS x11vnc-run.sh $@
